-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "landline" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "town" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "postcode" TEXT;
